// AUTO-GENERATED by tools/generate-schema-types.mjs — DO NOT EDIT
// Edit schema/entities.mjs and re-run: npm run types:gen

type QueryOp = 'eq' | 'like' | 'gte' | 'lte';
type FieldType = 'string' | 'integer' | 'number' | 'boolean' | 'enum' | 'timestamp';

type AllowedOpsFor<T extends FieldType> =
  T extends 'string' ? ('eq' | 'like') :
  T extends 'enum' ? 'eq' :
  T extends 'integer' | 'number' | 'timestamp' ? ('eq' | 'gte' | 'lte') :
  T extends 'boolean' ? 'eq' :
  never;

interface FieldPathMap {
  users: {
    'id': 'integer';
    'email': 'string';
    'password': 'string';
    'firstName': 'string';
    'lastName': 'string';
    'role': 'enum';
    'address.street': 'string';
    'address.city': 'string';
    'address.country': 'string';
    'address.zipCode': 'string';
    'phone': 'string';
    'status': 'enum';
    'createdAt': 'timestamp';
    'modifiedAt': 'timestamp';
  };
  categories: {
    'id': 'integer';
    'name': 'string';
    'description': 'string';
    'parentId': 'integer';
    'status': 'enum';
    'createdAt': 'timestamp';
    'modifiedAt': 'timestamp';
  };
  products: {
    'id': 'integer';
    'sellerId': 'integer';
    'categoryId': 'integer';
    'name': 'string';
    'description': 'string';
    'price': 'number';
    'stock': 'integer';
    'status': 'enum';
    'createdAt': 'timestamp';
    'modifiedAt': 'timestamp';
  };
  orders: {
    'id': 'integer';
    'userId': 'integer';
    'totalAmount': 'number';
    'shippingAddress.street': 'string';
    'shippingAddress.city': 'string';
    'shippingAddress.country': 'string';
    'shippingAddress.zipCode': 'string';
    'payment.method': 'enum';
    'payment.status': 'enum';
    'status': 'enum';
    'createdAt': 'timestamp';
    'modifiedAt': 'timestamp';
  };
  reviews: {
    'id': 'integer';
    'productId': 'integer';
    'userId': 'integer';
    'rating': 'integer';
    'comment': 'string';
    'createdAt': 'timestamp';
  };
}

type FilterConfig = {
  [E in keyof FieldPathMap]?: {
    [P in keyof FieldPathMap[E]]?: AllowedOpsFor<FieldPathMap[E][P]>[]
  }
};
